### ISSUE TITLE
Umm. Why can't you just get an  Developer certificate & sign it?

### ISSUE THREAD

**Issue by fredjohnsen** [Kiran-B/Jumpcut#2]
I really, really, really want to install this. I can't until you sign it.

**Comment by Kiran-B** [comment]
I do not have a paid developer account. AFAIK, developer ID or notarizing the app needs a paid account. Do let me know if there is a way to distribute a notarized/signed build without a paid account. 

You have a couple of choices at the moment:
1. Download the code and build/run the app
2. Allow the app to run accepting the risk that it was from an unidentified developer. Here is how you may do it:
- control-click (right-click) the app icon, then choose Open from the contextual menu.
- You will be presented with an alert, warning you that Jumpcut is from an unidentified developer. Click `Open` in the alert.

The above step shall be a one time thing.
More details here: https://support.apple.com/kb/ph25088

**Comment by fredjohnsen** [comment]
Thanks for updating!!!!!

**Comment by fredjohnsen** [comment]
I mean I guess I don't think $99 is a lot of money... That's what it costs for an individual & there are benefits for signing up: https://developer.apple.com/support/compare-memberships/ Also, you may qualify for a fee waiver: https://developer.apple.com/support/membership-fee-waiver/

**Comment by snark** [comment]
@fredjohnsen Hey, I'm the original developer -- there's a 64-bit-ready version prepping for release in the very near future at https://github.com/snark/jumpcut, including code signing/notarization for Catalina use.

@Kiran-B I'm not sure if there are any changes you'd like to merge back into the main repository -- if so, make some pull requests!

**Comment by Kiran-B** [comment]
> @Kiran-B I'm not sure if there are any changes you'd like to merge back into the main repository -- if so, make some pull requests!

Not really. Thanks for the awesome app. 

Closing this as there is a signed version of the app available.
