### ISSUE TITLE
The downloaded file from link is not compressed into a .zip

### ISSUE THREAD

**Issue by fredjohnsen** [Kiran-B/Jumpcut#3]
When I click the link to download it just places an app bundle in my Downloads folder. This is another reason to worry...

**Comment by Kiran-B** [comment]
Could this be due to your browser settings?
https://apple.stackexchange.com/questions/961/how-to-stop-safari-from-unzipping-files-after-download

I have verified this is Safari and Firefox(use `Save` rather than `open`).

**Comment by Kiran-B** [comment]
Closing this issue for now. Do reopen if you still facing problem with the download.
