### ISSUE TITLE
Purpose of this repo?

### ISSUE THREAD

**Issue by msagarpatel** [Kiran-B/Jumpcut#4]
I know the title sounds a bit negative, but I'm just genuinely trying to find out why this repo exists. The [official Jumpcut repo](https://github.com/snark/jumpcut) exists on Github, and this repo isn't a fork of that repo either. I was looking for the official repo, and this repo showed up higher in my search results than the official repo. To avoid confusion for others, would you consider

- updating the README, or
- making your repo a fork of the official repo, or
- archiving this repo?

If this repo was created before the version on GitHub existed, I just wanted to point out that there is an official repo on GitHub now. If this is the case, thanks for trying to preserve this project on GitHub!

**Comment by Kiran-B** [comment]
I personally use the app and there was a time when the original app did not work in the latest macOS and was not maintainned in sourceforge or Github. Primarily as it was 32-bit only.

So I created this repo from the https://sourceforge.net/projects/jumpcut/ and upgraded to make it work in the latest macOS.

Thanks for your message. I shall update the README to point to the original repo as I no longer intend to maintain it. I shall close this issue once the update to README is done.

**Comment by msagarpatel** [comment]
Thanks, Kiran! The updated documentation is helpful.
